[package]
name = "clpy"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.8"
clipboard-win = "5.3.1"
image = "0.25.1"
random-string = "1.0.0"
